### ISSUE TITLE
This extension crashes the entire Gnome

### ISSUE THREAD

**Issue by grongor** [kagesenshi/gnome-shell-extension-stealmyfocus#7]
Hello, I just discovered really surprising bug. I'm a web developer and I'm using `PhpStorm` editor. Some days ago I installed few `Gnome` extensions - `Steal my focus` was one of them. Suddenly `Gnome` started to crash really often so I tried to "debug" that and find out where is the problem. I really can't beliave it but I found out that `Gnome` crashes when I write statements like `return NULL;`. I tried it few more times - crash occurs after I type `<shift>NU`. I really don't know how is this possible. I tried to disable all of my extensions and then turned them on one by one so I found out that `Gnome` crashes due `Steal my focus`. I'm sorry but I'm "begginer" with Linux so I don't know which logs or other stuff should I provide - if you tell me I can post them here. I'm using `Debian Wheezy` with `Gnome Shell` (everything at most recent stable version).

**Comment by mlutonsky** [comment]
Hi, I have the same problem as @grongor - but the crash happens after pressing CTRL+SPACE (to invoke autocomplete tooltip). I'm using Debian Wheezy with Gnome Shell 3.4.2 (latest stable versions)
